# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Neural Finite Element Networks
author: Ethan Herron, Biswajit Khara, Baskar Ganapathysubramanian, Adarsh Krishnamurthy

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

extensions:
  - sphinxcontrib.bibtex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/idealab-isu/NeuralFiniteElementNetworks  # Online location of your book
  path_to_book: _build/html  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  logo: ""  # Path to your custom logo file (optional)
  # favicon: images/favicon.ico  # Path to a favicon (optional)

  # Theme settings
  theme:
    name: default
    # logo: images/logo.png  # Path to your custom logo file (optional)

# Add your Google Analytics code here
extrahead:
  - "<script async src='https://www.googletagmanager.com/gtag/js?id=G-SDR5B63V9G'></script>"
  - "<script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-SDR5B63V9G');
      </script>"